service: pupeteer-serverless

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: GET
          path: /
      - http:
          method: POST
          path: /newFormTest