service: pupeteer-serverless

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  deploymentMethod: direct
  region: us-east-1

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: GET
          path: /test
      - http:
          method: POST
          path: /newFormTest
      - http:
          method: GET
          path: /screenshot